# Generated by Django 2.1.7 on 2019-04-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
