# Generated by Django 3.2.9 on 2021-11-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(blank=True, choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('DEMORANDO', 'DEMORANDO')], default='')),
            ],
        ),
        migrations.CreateModel(
            name='Host_Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('porta',),
            },
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('portaServico', models.IntegerField(primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='host',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.AlterField(
            model_name='host',
            name='tipoHost',
            field=models.CharField(choices=[('Access Point', 'ACCESS POINT'), ('Desktop', 'DESKTOP'), ('Impressora', 'IMPRESSORA'), ('Notebook', 'NOTEBOOK'), ('Servidor', 'SERVIDOR'), ('Outros', 'OUTROS')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AddField(
            model_name='host_porta',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='Hosts.host'),
        ),
        migrations.AddField(
            model_name='host_porta',
            name='porta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porta', to='Hosts.porta'),
        ),
    ]
