# Generated by Django 3.2.9 on 2021-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porta',
            name='ping',
        ),
        migrations.AddField(
            model_name='evento',
            name='ping',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
