# Generated by Django 3.2.9 on 2021-11-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('DEMORANDO', 'DEMORANDO')], default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.AlterField(
            model_name='servico',
            name='porta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='Hosts.host'),
        ),
        migrations.AddField(
            model_name='evento',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='Hosts.host'),
        ),
    ]
