# Generated by Django 3.2.9 on 2021-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_auto_20211123_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ping',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
