# Generated by Django 3.2.9 on 2021-11-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_auto_20211119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='Hosts.host'),
        ),
    ]
