# Generated by Django 2.1.7 on 2019-04-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_auto_20190422_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='porta',
            field=models.PositiveIntegerField(default=0, max_length=5),
        ),
    ]
