# Generated by Django 3.2.9 on 2021-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_auto_20211109_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='evento',
            name='dataHora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='tipoHost',
            field=models.CharField(choices=[('Access Point', 'ACCESS POINT'), ('Desktop', 'DESKTOP'), ('Impressora', 'IMPRESSORA'), ('Notebook', 'NOTEBOOK'), ('Servidor', 'SERVIDOR'), ('Outros', 'OUTROS')], max_length=20),
        ),
    ]
