# Generated by Django 3.2.9 on 2021-11-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0003_alter_evento_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ping',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
