# Generated by Django 2.1.7 on 2019-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0004_auto_20190527_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
