# Generated by Django 2.2.1 on 2019-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0006_hosts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='servico',
            field=models.CharField(default='', max_length=100),
        ),
    ]
